# Generated by Django 3.2.3 on 2021-11-11 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_stripesubscription'),
        ('grocers_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocer',
            name='stripe_subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.stripesubscription'),
        ),
    ]
