# Generated by Django 3.2.3 on 2021-12-19 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocers_panel', '0004_shop_grocer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grocers_panel.food'),
        ),
    ]
