# Generated by Django 3.2.3 on 2021-12-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocers_panel', '0006_auto_20211219_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='meals',
            field=models.ManyToManyField(to='grocers_panel.Meal'),
        ),
        migrations.RemoveField(
            model_name='shop',
            name='food',
        ),
        migrations.AddField(
            model_name='shop',
            name='food',
            field=models.ManyToManyField(to='grocers_panel.Food'),
        ),
    ]
