# Generated by Django 3.2.3 on 2021-12-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocers_panel', '0008_auto_20211219_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='ratings',
            field=models.IntegerField(null=True),
        ),
    ]
