# Generated by Django 3.2.3 on 2021-12-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocers_panel', '0010_alter_shop_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='duration',
            field=models.PositiveSmallIntegerField(choices=[(1, '10 - 15'), (2, '20 - 25'), (3, '35 - 45'), (4, '55 - 65')], default=3),
        ),
    ]
