# Generated by Django 3.2.3 on 2022-07-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'popular'), (2, 'recommended'), (3, 'drinks')], default=2)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stars', models.IntegerField(default=0)),
                ('img', models.ImageField(blank=True, upload_to='food/%Y/%m/%d')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('people', models.IntegerField(default=0)),
                ('selected', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=155)),
            ],
            options={
                'verbose_name': 'Food',
                'verbose_name_plural': 'Foods',
                'ordering': ['created_at'],
            },
        ),
    ]
