# Generated by Django 3.2.3 on 2021-11-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'grocer'), (2, 'buyer'), (3, 'deliverer'), (4, 'admin')], default=2),
        ),
    ]
