# Generated by Django 3.2.3 on 2023-07-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_customuser_mail_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='ee', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
