# Generated by Django 3.2.3 on 2021-12-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocers_panel', '0005_alter_shop_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='meals',
        ),
        migrations.AddField(
            model_name='food',
            name='meals',
            field=models.ManyToManyField(null=True, to='grocers_panel.Meal'),
        ),
    ]
