# Generated by Django 3.2.3 on 2021-12-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocers_panel', '0009_alter_shop_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='ratings',
            field=models.IntegerField(default=0),
        ),
    ]
