# Generated by Django 3.2.3 on 2021-12-30 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocers_panel', '0012_alter_meal_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='ratings',
        ),
    ]
