# Generated by Django 3.2.3 on 2022-01-09 21:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('grocers_panel', '0014_auto_20220109_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('TR', 'Trier'), ('OF', 'Offres'), ('DI', 'Diététique')], default='TR', max_length=8),
        ),
        migrations.AlterField(
            model_name='meal',
            name='label',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('T', 'Toutes les offres'), ('J', "Jusqu'à 50% de réduction"), ('C', 'Choix de restaurants'), ('P', 'Commandez plus, économisez plus'), ('A', 'Articles gratuits'), ('M', 'Meals Deals')], default='T', max_length=11),
        ),
    ]
