# Generated by Django 3.2.3 on 2022-07-18 20:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grocers_panel', '0015_auto_20220109_2150'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food',
            new_name='FoodMeal',
        ),
    ]
