# Generated by Django 3.2.3 on 2023-07-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers_panel', '0009_auto_20221229_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id', '-ordered_date'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('O', 'Ordered'), ('D', 'Being Delivered'), ('R', 'Received'), ('F', 'Refund Requested')], default='P', max_length=1),
        ),
    ]
