# Generated by Django 3.2.3 on 2022-01-09 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers_panel', '0003_auto_20220109_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='orders',
        ),
    ]
