# Generated by Django 3.2.3 on 2022-07-24 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers_panel', '0007_auto_20220722_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='contact_person_phone',
            field=models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 05999999999', regex='^(\\d{2})\\d{8}$')]),
        ),
    ]
