# Generated by Django 3.2.3 on 2022-12-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers_panel', '0008_auto_20220724_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'ordering': ['-id'], 'verbose_name': 'Billing Address', 'verbose_name_plural': 'Billing Addresses'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='zip',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='latitude',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='longitude',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='address_type',
            field=models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping'), ('H', 'Home'), ('O', 'Office'), ('M', 'Other')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='street_address',
            field=models.CharField(max_length=255),
        ),
    ]
