# Generated by Django 3.2.3 on 2022-07-15 16:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('832f7562-e8a2-494f-a0a9-3f9d0c23ece6'), editable=False, primary_key=True, serialize=False)),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'popular'), (2, 'recommended')], default=2)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('stars', models.IntegerField(default=0)),
                ('img', models.ImageField(blank=True, upload_to='food/%Y/%m/%d')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Food',
                'verbose_name_plural': 'Foods',
                'ordering': ['created_at'],
            },
        ),
    ]
