# Generated by Django 3.2.3 on 2022-07-15 16:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c48ead70-2388-441c-80f4-588ce0cd0f88'), editable=False, primary_key=True, serialize=False),
        ),
    ]
