# Generated by Django 3.2.3 on 2022-07-15 17:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_api', '0002_alter_food_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1f271024-e149-4626-8b7b-168721ee6c1e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
