# Generated by Django 3.2.3 on 2022-07-15 17:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_api', '0003_auto_20220715_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
