# Generated by Django 3.2.3 on 2022-07-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_api', '0004_alter_food_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='location',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AddField(
            model_name='food',
            name='people',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='selected',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'popular'), (2, 'recommended'), (3, 'drinks')], default=2),
        ),
    ]
