# Generated by Django 3.2.3 on 2022-07-18 20:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_api', '0007_alter_food_food_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_pk',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, primary_key=False),
        ),
    ]
