# Generated by Django 3.2.3 on 2022-07-18 21:01

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('grocery_api', '0008_auto_20220718_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='food_id',
            new_name='food_pk',
        ),
    ]
