# Generated by Django 3.2.3 on 2022-07-18 22:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_api', '0008_auto_20220718_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
