# Generated by Django 3.2.3 on 2022-07-19 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_api', '0009_alter_food_id'),
    ]

    operations = [
    ]
