from collections import namedtuple

ORDER_STATUSES = namedtuple('ORDER_STATUSES', ['PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED'])._make(range(5))

ORDER_STATUSES = (
    (ORDER_STATUSES.PENDING, 'PENDING'),
    (ORDER_STATUSES.ACCEPTED, 'ACCEPTED'),
    (ORDER_STATUSES.REJECTED, 'REJECTED'),
    (ORDER_STATUSES.CANCELLED, 'CANCELLED'),
)
