# Generated by Django 3.2.3 on 2022-07-20 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocers_panel', '0017_remove_grocer_stripe_subscription'),
        ('admin_panel', '0005_category_highlights'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripeSubscription',
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default='delita', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='0606787045', max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 05999999999', regex='^(\\d{2})\\d{8}$')]),
            preserve_default=False,
        ),
    ]
